version: '{build}-{branch}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_folder: c:\projects\microorm.dapper.repositories
services: mssql2016
build_script:
- cmd: dotnet restore && dotnet pack MicroOrm.Dapper.Repositories -c Release
test_script:
- cmd: dotnet test MicroOrm.Dapper.Repositories.Tests\MicroOrm.Dapper.Repositories.Tests.csproj -c Release
artifacts:
- path: '**\*.nupkg'
  name: All Nupkg
deploy:
- provider: Environment
  name: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
notifications:
- provider: Email
  to:
  - sergey.kuznetsov@hotmail.com
  subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true